# Nome da Actions:
name: Snake Game

# Controlador do tempo que será feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas
    - cron: "0 */5 * * *"
  
  # Permite executar manualmente pela aba Actions (usado para testes)
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      # Faz o checkout do repositório para o ambiente de trabalho
      - uses: actions/checkout@v2

      # Repositório que será utilizado para gerar os arquivos da animação da cobrinha
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} # Usa o nome do usuário do repositório
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Para fazer o push das alterações para a branch 'output'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Agora faz o push na branch 'output'
          force: true

      # Publicar os arquivos da animação no GitHub Pages na branch 'output'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
