name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake Game from GitHub user contribution grid
        uses: Platane/snk@v2
        with:
          github_user_name: PedroFurtadoC
          gif_out_path: dist/github-contribution-grid-snake.svg

      - name: Push Snake Game to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
